services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      employees-network:
        ipv4_address: 10.10.45.10
    ports:
      - "8080:8080"

networks:
  employees-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.45.0/24
